AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Default: dev
Globals:
  Function:
    Runtime: python3.9
    Handler: app.handler
    MemorySize: 256
    Timeout: 180
    Environment:
      Variables:
        ENVIRONMENT:
          Ref: Environment
        IMAGE_S3_BUCKET_NAME:
          Ref: ImageS3Bucket
        IMAGE_METADATA_TABLE_NAME:
          Ref: ImageMetadataTable
        LOCAL_STACK_ENDPOINT_URL: http://localhost.localstack.cloud:4566
Resources:
  ImageS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: image-storage-bucket-${Environment}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 5
      Tags:
      - Key: Company
        Value: MontyCloud
      - Key: Purpose
        Value: Assignment
    Metadata:
      SamResourceId: ImageS3Bucket
  ImageMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: image_metadata_table_${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: image_id
        AttributeType: S
      KeySchema:
      - AttributeName: image_id
        KeyType: HASH
    Metadata:
      SamResourceId: ImageMetadataTable
  ImageStorageAPI:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Company: MontyCloud
        Purpose: Assignment
      TracingEnabled: true
      MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: /*
        HttpMethod: '*'
        MetricsEnabled: true
        DataTraceEnabled: true
      Name: ImageStorageApiGateway
      OpenApiVersion: 3.0.2
      StageName: v1
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://localstack-resources-bucket/imageupload/af4c23737ec689432c0a84bb2eef8dc0
    Metadata:
      SamResourceId: ImageStorageAPI
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Uploads image to s3 and saves metadata to dynamodb
      FunctionName: upload_image
      Tracing: Active
      CodeUri: s3://localstack-resources-bucket/imageupload/83047114f0e32d820e2bf7293f3a7542
      Events:
        UploadImageAPI:
          Type: Api
          Properties:
            Path: /image/upload
            Method: post
            RestApiId:
              Ref: ImageStorageAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Tags:
        Company: MontyCloud
        Purpose: Assignment
    Metadata:
      SamResourceId: UploadImageFunction
  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: list images from dynamodb
      FunctionName: list_images
      Tracing: Active
      CodeUri: s3://localstack-resources-bucket/imageupload/e53c092769d5699726fbe6b643095d51
      Events:
        ListImagesAPI:
          Type: Api
          Properties:
            Path: /images/list
            Method: get
            RestApiId:
              Ref: ImageStorageAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Tags:
        Company: MontyCloud
        Purpose: Assignment
    Metadata:
      SamResourceId: ListImagesFunction
  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: delete image from s3 and dynamodb
      FunctionName: delete_image
      Tracing: Active
      CodeUri: s3://localstack-resources-bucket/imageupload/53c13d4587d4cdeefeafc1ce2f334033
      Events:
        DeleteImageAPI:
          Type: Api
          Properties:
            Path: /image/{image_id}
            Method: delete
            RestApiId:
              Ref: ImageStorageAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Tags:
        Company: MontyCloud
        Purpose: Assignment
    Metadata:
      SamResourceId: DeleteImageFunction
  DownloadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Download image from s3 based on image id
      FunctionName: download_image
      Tracing: Active
      CodeUri: s3://localstack-resources-bucket/imageupload/dd6a7f3d42da4f50b63151e4b0b9a9de
      Events:
        DownloadImageAPI:
          Type: Api
          Properties:
            Path: /image/{image_id}
            Method: get
            RestApiId:
              Ref: ImageStorageAPI
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'
      Tags:
        Company: MontyCloud
        Purpose: Assignment
    Metadata:
      SamResourceId: DownloadImageFunction
